on:
  - push

jobs:
  test:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        racket-variant: ['BC', 'CS']
        racket-version: ['stable']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Install Package and its Dependencies
        run: raco pkg install x64asm-lib/ x64asm-test/
      - name: Run Tests
        run: raco test -p x64asm-test
      - name: Build Docs
        if: matrix.os == 'ubuntu-latest' 
        run: raco pkg install x64asm/ x64asm-doc/

